server:
  port: 8082
  servlet:
    context-path: /mq-rest

spring:
  rabbitmq:
    addresses: localhost:5672
    username: admin
    password: admin
    virtual-host: /gary-test
    connection-timeout: 15000
    publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 5
        max-concurrency: 10
      order:
        queue:
          name: queue-2
          durable: true
        key: springboot.*
        exchange:
          name: exchange-2
          durable: true
          type: topic
          ignoreDeclarationExceptions: true