spring:
  application:
    name: member-server
  redis:
    database: 0
    #单机版
    #    host: 127.0.0.1
    #    port: 6379
    #    password: 123456
    #      pool:
    #        max-idle: 100
    #        min-idle: 1
    #        max-active: 1000
    #        max-wait: -1
    #集群版
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    timeout: 10000
    cluster:
      nodes:
        - 10.200.132.171:7000
        - 10.200.132.171:7001
        - 10.200.132.171:7002
        - 10.200.132.171:7003
        - 10.200.132.171:7004
        - 10.200.132.171:7005
server:
  port: 9992
  servlet:
    context-path: /cluster-redis
